hello_world = [
    ("English", "Hello, World!"),
    ("Spanish", "¡Hola, Mundo!"),
    ("French", "Bonjour, le Monde!"),
    ("German", "Hallo, Welt!"),
    ("Italian", "Ciao, Mondo!"),
    ("Portuguese", "Olá, Mundo!"),
    ("Dutch", "Hallo, Wereld!"),
    ("Danish", "Hej, Verden!"),
    ("Norwegian", "Hei, Verden!"),
    ("Swedish", "Hej, Världen!"),
    ("Finnish", "Hei, Maailma!"),
    ("Icelandic", "Halló, heimur!"),
    ("Polish", "Witaj, Świecie!"),
    ("Czech", "Ahoj, světe!"),
    ("Slovak", "Ahoj, svet!"),
    ("Slovenian", "Pozdravljen, svet!"),
    ("Serbian", "Zdravo, svete!"),
    ("Croatian", "Bok, svijete!"),
    ("Bosnian", "Pozdrav, svijete!"),
    ("Bulgarian", "Здравей, свят!"),
    ("Ukrainian", "Привіт, світ!"),
    ("Russian", "Привет, мир!"),
    ("Belarusian", "Прывітанне, свет!"),
    ("Lithuanian", "Sveiki, pasauli!"),
    ("Latvian", "Sveika, pasaule!"),
    ("Estonian", "Tere, maailm!"),
    ("Hungarian", "Szia, Világ!"),
    ("Romanian", "Salut, Lume!"),
    ("Albanian", "Përshëndetje, Botë!"),
    ("Greek", "Γεια σου, Κόσμε!"),
    ("Turkish", "Merhaba, Dünya!"),
    ("Hebrew", "שלום, עולם!"),
    ("Arabic", "مرحباً, يا عالم!"),
    ("Persian", "سلام دنیا!"),
    ("Urdu", "ہیلو، دنیا!"),
    ("Hindi", "नमस्ते, दुनिया!"),
    ("Bengali", "ওহে, বিশ্ব!"),
    ("Tamil", "வணக்கம், உலகம்!"),
    ("Telugu", "హలో, ప్రపంచం!"),
    ("Kannada", "ಹಲೋ, ಜಗತ್ತು!"),
    ("Malayalam", "ഹലോ, ലോകം!"),
    ("Gujarati", "નમસ્તે, દુનિયા!"),
    ("Punjabi", "ਸਤ ਸ੍ਰੀ ਅਕਾਲ, ਦੁਨਿਆ!"),
    ("Sinhala", "ආයුබෝවන්, ලෝකය!"),
    ("Thai", "สวัสดี, โลก!"),
    ("Khmer", "ជំរាបសួរ, ពិភពលោក!"),
    ("Lao", "ສະບາຍດີ, ໂລກ!"),
    ("Burmese", "မင်္ဂလာပါ, ကမ္ဘာလောက!"),
    ("Vietnamese", "Xin chào, Thế giới!"),
    ("Indonesian", "Halo, Dunia!"),
    ("Malay", "Helo, Dunia!"),
    ("Filipino/Tagalog", "Kumusta, Mundo!"),
    ("Cebuano", "Kamusta, Kalibutan!"),
    ("Chinese (Simplified)", "你好，世界！"),
    ("Chinese (Traditional)", "你好，世界！"),
    ("Japanese", "こんにちは、世界！"),
    ("Korean", "안녕하세요, 세계!"),
    ("Mongolian", "Сайн байна уу, дэлхий!"),
    ("Kazakh", "Сәлем, Әлем!"),
    ("Tajik", "Салом, Дунё!"),
    ("Uzbek", "Salom, Dunyo!"),
    ("Kyrgyz", "Сәлем, дүйнө!"),
    ("Azerbaijani", "Salam, Dünya!"),
    ("Georgian", "Გამარჯობა, მსოფლიო!"),
    ("Armenian", "Բարեւ, աշխարհ!"),
    ("Zulu", "Sawubona, Mhlaba!"),
    ("Sotho", "Dumela, Lefatshe!"),
    ("Xhosa", "Molo, Lizwe!"),
    ("Shona", "Mhoro, Nyika!"),
    ("Swahili", "Habari, Dunia!"),
    ("Amharic", "ሰላም, ዓለም!"),
    ("Hausa", "Sannu, Duniya!"),
    ("Yoruba", "Ẹ ku aaro, Aye!"),
    ("Igbo", "Ndewo, Ụwa!"),
    ("Haitian Creole", "Bonjou, Mond!"),
    ("Basque", "Kaixo, Mundua!"),
    ("Galician", "Ola, Mundo!"),
    ("Catalan", "Hola, Món!"),
    ("Welsh", "Sut mae, Byd!"),
    ("Irish", "Dia dhuit, a Domhan!"),
    ("Scottish Gaelic", "Halò, a Shaoghail!"),
    ("Luxembourgish", "Moien, Welt!"),
    ("Esperanto", "Saluton, Mondo!"),
    ("Guarani", "Mba'éichapa, Yvóra!"),
    ("Samoan", "Talofa, Lalolagi!"),
    ("Maori", "Kia ora, e Ao!"),
    ("Fijian", "Bula, Vuravura!"),
    ("Hawaiian", "Aloha, Honua!"),
    ("Navajo", "Yá'át'ééh, Nahasdzáán!"),
    ("Afrikaans", "Hallo, Wêreld!"),
    ("Nepali", "नमस्ते, संसार!"),
    ("Latin", "Salve, Munde!"),
    ("Malagasy", "Salama, Tontolo!"),
    ("Somali", "Salaam, Dunida!"),
    ("Tigrinya", "ሰላም, ዓለም!"),
    ("Wolof", "Salaam, Adduna!"),
    ("Kinyarwanda", "Muraho, Isi!"),
    ("Luganda", "Kulika, Ensi!"),
    ("Chichewa", "Moni, Dziko!"),
    ("Tswana", "Dumela, Lefatshe!"),
]

print("Here is Hello World is one hundred different languages!")
for language, greeting in hello_world:
    print(f"{language} - {greeting}")
